import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../quran/quran_service.dart';

class HomePage extends StatefulWidget { const HomePage({super.key,required this.onNavigate,required this.onToggleTheme}); final ValueChanged<int> onNavigate; final VoidCallback onToggleTheme; @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage>{ late DateTime _today; Timer? _timer; int _offset=0; @override void initState(){super.initState();_today=_dateOnly(DateTime.now());_schedule();} DateTime _dateOnly(DateTime v)=>DateTime(v.year,v.month,v.day); int get _daily=>((_today.difference(DateTime(2024,1,1)).inDays+_offset)%6236)+1; void _another()=>setState(()=>_offset=(_offset+1)%6236); void _schedule(){final now=DateTime.now();final next=DateTime(now.year,now.month,now.day+1);_timer=Timer(next.difference(now)+const Duration(seconds:1),(){if(!mounted)return;setState(()=>_today=_dateOnly(DateTime.now()));_schedule();});} @override void dispose(){_timer?.cancel();super.dispose();}
@override Widget build(BuildContext context){final t=Theme.of(context);final dark=t.brightness==Brightness.dark;return LayoutBuilder(builder:(context,c)=>SingleChildScrollView(padding:EdgeInsets.all(c.maxWidth>700?32:20),child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:980),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
Row(children:[Container(width:58,height:58,clipBehavior:Clip.antiAlias,decoration:BoxDecoration(borderRadius:BorderRadius.circular(16)),child:SvgPicture.asset('assets/nuur_path_logo.svg')),const SizedBox(width:12),Expanded(child:Text('Miqra',style:t.textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w900))),IconButton.filledTonal(tooltip:dark?'Light mode':'Dark mode',onPressed:widget.onToggleTheme,icon:Icon(dark?Icons.light_mode_rounded:Icons.dark_mode_rounded))]),
const SizedBox(height:22),Text('Assalamu Alaikum',style:t.textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('Read, listen, memorize and revise — all in one place.'),const SizedBox(height:24),
Row(children:[Expanded(child:Text('Daily Ayah',style:t.textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800))),Text('${_today.day.toString().padLeft(2,'0')}/${_today.month.toString().padLeft(2,'0')}/${_today.year}')]),const SizedBox(height:10),
FutureBuilder<AyahData>(key:ValueKey(_daily),future:QuranService.loadAyah(_daily),builder:(context,s){if(!s.hasData)return const Card(child:Padding(padding:EdgeInsets.all(28),child:Center(child:CircularProgressIndicator())));final a=s.data!;return Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text('Surah ${a.surah} • Ayah ${a.ayah}',style:t.textTheme.labelLarge),const SizedBox(height:14),Text(a.arabic,textDirection:TextDirection.rtl,textAlign:TextAlign.right,style:const TextStyle(fontSize:28,height:1.9)),const SizedBox(height:10),Text(a.transliteration,style:const TextStyle(fontStyle:FontStyle.italic)),const SizedBox(height:8),Text(a.english),const SizedBox(height:8),Text(a.urdu,textDirection:TextDirection.rtl,textAlign:TextAlign.right),const SizedBox(height:16),Wrap(spacing:10,children:[FilledButton.tonalIcon(onPressed:_another,icon:const Icon(Icons.shuffle_rounded),label:const Text('Another Ayah')),FilledButton.icon(onPressed:()=>widget.onNavigate(1),icon:const Icon(Icons.menu_book_rounded),label:const Text('Open Quran'))])])));}),
const SizedBox(height:24),Text('Quick actions',style:t.textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:12),Wrap(spacing:12,runSpacing:12,children:[_Action(title:'Quran Reader',icon:Icons.menu_book_rounded,onTap:()=>widget.onNavigate(1)),_Action(title:'My Hifz',icon:Icons.auto_graph_rounded,onTap:()=>widget.onNavigate(2)),_Action(title:'Mutashabihat',icon:Icons.auto_awesome_motion_rounded,onTap:()=>widget.onNavigate(3)),_Action(title:'Tasbih',icon:Icons.add_circle_rounded,onTap:()=>widget.onNavigate(4))])
])))));}}
class _Action extends StatelessWidget{const _Action({required this.title,required this.icon,required this.onTap});final String title;final IconData icon;final VoidCallback onTap;@override Widget build(BuildContext c)=>SizedBox(width:230,child:Card(child:InkWell(onTap:onTap,child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[Icon(icon,size:28),const SizedBox(width:12),Expanded(child:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)))])))));}
